const PUBLIC_GAPI = "AIzaSyDTVU5CPuioayuZWRA6ND6l97_cvpOsW6I";
const PUBLIC_API_MAPTILER = "HYfdFgCyq2QEA4rDwPqX";
const PUBLIC_GOOGLE_CLIENT_ID = "655479452799-emhkngopa8qghpm50d6kd1m1f2vrttdd.apps.googleusercontent.com";
const PUBLIC_GOOGLE_CLIENT_SECRET = "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";
export {
  PUBLIC_API_MAPTILER as P,
  PUBLIC_GAPI as a,
  PUBLIC_GOOGLE_CLIENT_SECRET as b,
  PUBLIC_GOOGLE_CLIENT_ID as c
};
